/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    media: Media;
    companies: Company;
    contacts: Contact;
    tenders: Tender;
    'tender-documents': TenderDocument;
    requirements: Requirement;
    capabilities: Capability;
    'checklist-templates': ChecklistTemplate;
    'tender-checklists': TenderChecklist;
    tasks: Task;
    'ai-jobs': AiJob;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    tenders: TendersSelect<false> | TendersSelect<true>;
    'tender-documents': TenderDocumentsSelect<false> | TenderDocumentsSelect<true>;
    requirements: RequirementsSelect<false> | RequirementsSelect<true>;
    capabilities: CapabilitiesSelect<false> | CapabilitiesSelect<true>;
    'checklist-templates': ChecklistTemplatesSelect<false> | ChecklistTemplatesSelect<true>;
    'tender-checklists': TenderChecklistsSelect<false> | TenderChecklistsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    'ai-jobs': AiJobsSelect<false> | AiJobsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  /**
   * Hex, e.g. #2f5fe0
   */
  accentColor?: string | null;
  /**
   * Never send this tenant’s documents to external AI providers.
   */
  privateProcessing?: boolean | null;
  modelTier?: ('standard' | 'high') | null;
  /**
   * Per-tenant wording overrides
   */
  terminology?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName?: string | null;
  role: 'admin' | 'bid_manager' | 'contributor' | 'viewer';
  /**
   * Our staff. Can see every tenant. Never grant to a customer.
   */
  isPlatformAdmin?: boolean | null;
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  kind?: ('client' | 'prospect' | 'competitor' | 'partner') | null;
  country?: string | null;
  industry?: string | null;
  website?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  tenant?: (number | null) | Tenant;
  fullName: string;
  company?: (number | null) | Company;
  jobTitle?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Primary contact
   */
  isPrimary?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenders".
 */
export interface Tender {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * e.g. ITT-2026-0042
   */
  reference?: string | null;
  client?: (number | null) | Company;
  country?: string | null;
  submissionDeadline?: string | null;
  estimatedValue?: number | null;
  stage?: ('identified' | 'qualifying' | 'preparing' | 'submitted' | 'won' | 'lost' | 'abandoned') | null;
  scope?: string | null;
  owner?: (number | null) | User;
  decision?: ('bid' | 'no_bid' | 'hold') | null;
  decidedAt?: string | null;
  decisionReason?: string | null;
  decidedBy?: (number | null) | User;
  processingStatus?: ('none' | 'processing' | 'ready' | 'failed') | null;
  /**
   * TenderMetadata contract payload, evidence included
   */
  aiMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  engineJobId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tender-documents".
 */
export interface TenderDocument {
  id: number;
  tenant?: (number | null) | Tenant;
  tender: number | Tender;
  documentType?: ('itt' | 'specification' | 'boq' | 'contract' | 'drawing' | 'addendum' | 'other') | null;
  ingestionStatus?: ('not_processed' | 'processing' | 'ingested' | 'failed') | null;
  engineDocumentId?: string | null;
  engineJobId?: string | null;
  ingestionError?: string | null;
  pageCount?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requirements".
 */
export interface Requirement {
  id: number;
  tenant?: (number | null) | Tenant;
  tender: number | Tender;
  text: string;
  category?:
    | (
        | 'technical'
        | 'commercial'
        | 'contractual'
        | 'qualification'
        | 'certification'
        | 'documentation'
        | 'submission'
        | 'schedule'
        | 'other'
      )
    | null;
  mandatory?: ('yes' | 'no' | 'unclear') | null;
  /**
   * Where this came from. Never leave a fact unsourced.
   */
  evidence?:
    | {
        /**
         * Source document
         */
        document?: (number | null) | TenderDocument;
        page?: number | null;
        /**
         * e.g. 7.3.2
         */
        clause?: string | null;
        /**
         * Heading trail
         */
        sectionPath?: string | null;
        /**
         * Verbatim text from the source that supports this fact
         */
        quote: string;
        method?: ('human' | 'llm' | 'rule' | 'ocr_llm') | null;
        /**
         * 0-1
         */
        confidence?: number | null;
        /**
         * Quote confirmed against source
         */
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  complianceStatus?: ('compliant' | 'partial' | 'gap' | 'unknown') | null;
  /**
   * What we have that satisfies this requirement
   */
  matchedCapabilities?: (number | Capability)[] | null;
  complianceRationale?: string | null;
  assignee?: (number | null) | User;
  reviewStatus?: ('pending' | 'accepted' | 'rejected') | null;
  /**
   * Flagged because it could not be verified
   */
  needsReview?: boolean | null;
  note?: string | null;
  engineRequirementId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capabilities".
 */
export interface Capability {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  kind: 'capability' | 'certification' | 'project_reference' | 'product' | 'equipment';
  category?: string | null;
  description?: string | null;
  issuer?: string | null;
  validUntil?: string | null;
  certificateNumber?: string | null;
  client?: (number | null) | Company;
  year?: number | null;
  value?: number | null;
  country?: string | null;
  /**
   * Certificate, datasheet or reference letter
   */
  evidenceDocument?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checklist-templates".
 */
export interface ChecklistTemplate {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * e.g. Oil & Gas
   */
  industry?: string | null;
  /**
   * e.g. ILI inspection
   */
  tenderType?: string | null;
  description?: string | null;
  sections: {
    title: string;
    items?:
      | {
          label: string;
          category?:
            | (
                | 'technical'
                | 'commercial'
                | 'legal'
                | 'qualification'
                | 'certification'
                | 'documentation'
                | 'submission'
              )
            | null;
          required?: boolean | null;
          guidance?: string | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tender-checklists".
 */
export interface TenderChecklist {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  tender: number | Tender;
  sourceTemplate?: (number | null) | ChecklistTemplate;
  /**
   * Generated by the engine and awaiting human review (Phase 2).
   */
  aiProposed?: boolean | null;
  sections?:
    | {
        title: string;
        items?:
          | {
              label: string;
              status?: ('todo' | 'in_progress' | 'done' | 'na') | null;
              owner?: (number | null) | User;
              required?: boolean | null;
              notes?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  tender?: (number | null) | Tender;
  assignee?: (number | null) | User;
  status?: ('todo' | 'in_progress' | 'blocked' | 'done') | null;
  priority?: ('low' | 'normal' | 'high') | null;
  dueDate?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-jobs".
 */
export interface AiJob {
  id: number;
  tenant?: (number | null) | Tenant;
  tender?: (number | null) | Tender;
  type: 'ingest' | 'extract_metadata' | 'extract_requirements' | 'generate_checklist' | 'compliance' | 'score';
  state?: ('queued' | 'running' | 'succeeded' | 'failed') | null;
  engineJobId?: string | null;
  progress?: number | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'tenders';
        value: number | Tender;
      } | null)
    | ({
        relationTo: 'tender-documents';
        value: number | TenderDocument;
      } | null)
    | ({
        relationTo: 'requirements';
        value: number | Requirement;
      } | null)
    | ({
        relationTo: 'capabilities';
        value: number | Capability;
      } | null)
    | ({
        relationTo: 'checklist-templates';
        value: number | ChecklistTemplate;
      } | null)
    | ({
        relationTo: 'tender-checklists';
        value: number | TenderChecklist;
      } | null)
    | ({
        relationTo: 'tasks';
        value: number | Task;
      } | null)
    | ({
        relationTo: 'ai-jobs';
        value: number | AiJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  accentColor?: T;
  privateProcessing?: T;
  modelTier?: T;
  terminology?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  isPlatformAdmin?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  kind?: T;
  country?: T;
  industry?: T;
  website?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  tenant?: T;
  fullName?: T;
  company?: T;
  jobTitle?: T;
  email?: T;
  phone?: T;
  isPrimary?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenders_select".
 */
export interface TendersSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  reference?: T;
  client?: T;
  country?: T;
  submissionDeadline?: T;
  estimatedValue?: T;
  stage?: T;
  scope?: T;
  owner?: T;
  decision?: T;
  decidedAt?: T;
  decisionReason?: T;
  decidedBy?: T;
  processingStatus?: T;
  aiMetadata?: T;
  engineJobId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tender-documents_select".
 */
export interface TenderDocumentsSelect<T extends boolean = true> {
  tenant?: T;
  tender?: T;
  documentType?: T;
  ingestionStatus?: T;
  engineDocumentId?: T;
  engineJobId?: T;
  ingestionError?: T;
  pageCount?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requirements_select".
 */
export interface RequirementsSelect<T extends boolean = true> {
  tenant?: T;
  tender?: T;
  text?: T;
  category?: T;
  mandatory?: T;
  evidence?:
    | T
    | {
        document?: T;
        page?: T;
        clause?: T;
        sectionPath?: T;
        quote?: T;
        method?: T;
        confidence?: T;
        verified?: T;
        id?: T;
      };
  complianceStatus?: T;
  matchedCapabilities?: T;
  complianceRationale?: T;
  assignee?: T;
  reviewStatus?: T;
  needsReview?: T;
  note?: T;
  engineRequirementId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capabilities_select".
 */
export interface CapabilitiesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  kind?: T;
  category?: T;
  description?: T;
  issuer?: T;
  validUntil?: T;
  certificateNumber?: T;
  client?: T;
  year?: T;
  value?: T;
  country?: T;
  evidenceDocument?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checklist-templates_select".
 */
export interface ChecklistTemplatesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  industry?: T;
  tenderType?: T;
  description?: T;
  sections?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              label?: T;
              category?: T;
              required?: T;
              guidance?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tender-checklists_select".
 */
export interface TenderChecklistsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  tender?: T;
  sourceTemplate?: T;
  aiProposed?: T;
  sections?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              label?: T;
              status?: T;
              owner?: T;
              required?: T;
              notes?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  tender?: T;
  assignee?: T;
  status?: T;
  priority?: T;
  dueDate?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-jobs_select".
 */
export interface AiJobsSelect<T extends boolean = true> {
  tenant?: T;
  tender?: T;
  type?: T;
  state?: T;
  engineJobId?: T;
  progress?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}