# Generated by Django 5.2.17 on 2026-08-27 07:04

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("tenders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltender",
            name="requirements_job_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="historicaltender",
            name="requirements_status",
            field=models.CharField(default="pending", max_length=16),
        ),
        migrations.AddField(
            model_name="tender",
            name="requirements_job_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="tender",
            name="requirements_status",
            field=models.CharField(default="pending", max_length=16),
        ),
        migrations.CreateModel(
            name="HistoricalRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "engine_requirement_id",
                    models.CharField(db_index=True, max_length=64),
                ),
                ("text", models.TextField()),
                ("category", models.CharField(max_length=32)),
                ("mandatory", models.BooleanField(null=True)),
                ("evidence", models.JSONField(default=list)),
                ("confidence", models.FloatField(default=0.0)),
                ("needs_review", models.BooleanField(default=False)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tenders.tender",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical requirement",
                "verbose_name_plural": "historical requirements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "engine_requirement_id",
                    models.CharField(db_index=True, max_length=64),
                ),
                ("text", models.TextField()),
                ("category", models.CharField(max_length=32)),
                ("mandatory", models.BooleanField(null=True)),
                ("evidence", models.JSONField(default=list)),
                ("confidence", models.FloatField(default=0.0)),
                ("needs_review", models.BooleanField(default=False)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="tenders.tender",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tender", "engine_requirement_id"),
                        name="unique_requirement_per_tender",
                    )
                ],
            },
        ),
    ]
