# Generated by Django 5.2.17 on 2026-08-27 07:05

import tenders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0002_historicaltender_requirements_job_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltenderdocument",
            name="file",
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="tenderdocument",
            name="file",
            field=models.FileField(
                max_length=1024, upload_to=tenders.models.document_upload_path
            ),
        ),
    ]
