import type { CollectionConfig } from 'payload'

/** A checklist instance applied to one tender, with per-item progress. */
export const TenderChecklists: CollectionConfig = {
  slug: 'tender-checklists',
  admin: { useAsTitle: 'name', group: 'Tenders', defaultColumns: ['name', 'tender', 'sourceTemplate'] },
  fields: [
    { name: 'name', type: 'text', required: true },
    { name: 'tender', type: 'relationship', relationTo: 'tenders', required: true, index: true },
    { name: 'sourceTemplate', type: 'relationship', relationTo: 'checklist-templates' },
    {
      name: 'aiProposed',
      type: 'checkbox',
      defaultValue: false,
      admin: { description: 'Generated by the engine and awaiting human review (Phase 2).' },
    },
    {
      name: 'sections',
      type: 'array',
      fields: [
        { name: 'title', type: 'text', required: true },
        {
          name: 'items',
          type: 'array',
          fields: [
            { name: 'label', type: 'text', required: true },
            {
              type: 'row',
              fields: [
                {
                  name: 'status',
                  type: 'select',
                  defaultValue: 'todo',
                  admin: { width: '40%' },
                  options: [
                    { label: 'To do', value: 'todo' },
                    { label: 'In progress', value: 'in_progress' },
                    { label: 'Done', value: 'done' },
                    { label: 'Not applicable', value: 'na' },
                  ],
                },
                { name: 'owner', type: 'relationship', relationTo: 'users', admin: { width: '30%' } },
                { name: 'required', type: 'checkbox', defaultValue: true, admin: { width: '30%' } },
              ],
            },
            { name: 'notes', type: 'textarea' },
          ],
        },
      ],
    },
  ],
}
